### ISSUE TITLE
Installion issues

### ISSUE THREAD

**Issue by guamaral89** [tugstugi/mongolian-speech-recognition#10]
Sain bnu?
Bi uurii chin ajillig sullgaj joohon yum sudlah gesen yum. Daanch installation deere gatschihlaa. 1).Docker file --> workspace uurin chin file uu? ugui bol workspace file github-d baih estio file uu?
2). Apex error bas uguud bh yum 
Traceback (most recent call last):
  File "train.py", line 12, in <module>
    import apex
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apex/__init__.py", line 18, in <module>
    from apex.interfaces import (ApexImplementation,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apex/interfaces.py", line 10, in <module>
    class ApexImplementation(object):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/apex/interfaces.py", line 14, in ApexImplementation
    implements(IApex)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zope/interface/declarations.py", line 706, in implements
    raise TypeError(_ADVICE_ERROR % 'implementer')
TypeError: Class advice impossible in Python3.  Use the @implementer class decorator instead.
Install hiihed tusalj ugnuu? 
Bayarlalaa

**Comment by tugstugi** [comment]
```
cd docker && docker build . -t mongolian-speech-recognition
./docker/launch_docker.sh
cd /workspace/mongolian-speech-recognition
```
Docker дотор Apex суусан байгаа.
