### ISSUE TITLE
broken links in dataset download script

### ISSUE THREAD

**Issue by saihnii4** [tugstugi/mongolian-speech-recognition#15]
the storage bucket used to pull the Mongolian Bible dataset no longer has the Mongolian version available for download.

if anyone still has a copy of the original .zip files, I would be eternally grateful.

```
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python3', 'dl_mbspeech.py']' command failed.  (See above for error)
downloading https://s3.us-east-2.amazonaws.com/bible.davarpartners.com/Mongolian/01_Genesis.zip...
extracting '01_Genesis.zip'...

2MB [00:00, 766.57MB/s]
Traceback (most recent call last):
  File "/Users/xd/Code/mongolian-speech-recognition/datasets/dl_mbspeech.py", line 37, in <module>
    zipfile = ZipFile(bible_book_file_path)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/zipfile.py", line 1257, in __init__
    self._RealGetContents()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/zipfile.py", line 1324, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by zhao-shuyang** [comment]
I got the same problem with the download script

**Comment by zhao-shuyang** [comment]
Got the same problem. Anywhere this can be still downloaded?

**Comment by yygg678** [comment]
@bayartsogt-ya 
the storage bucket used to pull the Mongolian Bible dataset no longer has the Mongolian version available for download.
if you still has a copy of the original .zip files, share me, I would be eternally grateful.
